version: '3.5'
services:
  atest:
    image: abc
    command: echo test
    volumes:
{{range $i, $v := .myvols}}
        - {{$v}}
{{end}}

  hello-world:
    image: hello-world
    ports:
{{range $i, $v := .ports}} 
      - {{$v}}
{{end}}
volumes: {{.volumes}}
